<div class="container">
	<div class="row pt-5 px-5">
		<div class="col-md-12 px-4 col-sm-12  mb-2" style="font-size: 15px; margin: auto;" align="center">
			<nav class="navbar navbar-expand-lg">
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item mr-1">
					        <a class="nav-link link-option desable-link alert alert-primary" id="pessoal" href="/candidato/adicionar">Pessoais</a>
					    </li>
					    <li class="nav-item mr-1">
					        <a class="nav-link link-option desable-link alert alert-primary" id="formacao" href="/curso/adicionar">Formação</a>
					    </li>
					    <li class="nav-item mr-1">
					        <a class="nav-link link-option desable-link alert alert-primary" id="experiencia" href="/candidato/adicionar">Experiencias</a>
					    </li>
					</ul>
				</div>
			</nav>
		</div>
	</div>
	<div class="row pb-5 px-5">
		<form class="col" method="post" action="/candidato/savar">
			<fieldset><legend>Experienias</legend>
				<div class="row">
					<div class="col">
						<div class="form-group">
							<label for="empresa">Empresa</label>
							<input type="text" name="empresa" id="empresa"class="form-control form-control-sm" required="required">
						</div>
						<div class="form-group">
							<label for="cargo">Cargo</label>
							<input type="text" name="cargo" id="cargo"class="form-control form-control-sm" required="required">
						</div>
						<div class="form-group">
							<label for="desc_cargo">Descrição do cargo</label>
							<textarea required="required" name="desc_cargo"id="desc_cargo" class="form-control form-control-sm"></textarea>
						</div>
					</div>
					<div class="col">
						<div class="form-group">
							<label for="inicio">Inicio</label>
							<input type="date" name="inicio" id="inicio"class="form-control form-control-sm" required="required">
						</div>
						<div class="form-group">
							<label for="fim">Fim</label>
							<input type="date" name="fim" id="fim"class="form-control form-control-sm" required="required">
						</div>
						<div class="form-group">
							<label for="atual">Atual ?</label>
							<select name="atual" id="atual"class="form-control form-control-sm" required="required">
								<option value="1">Sim</option>
								<option value="2">Não</option>
							</select>
						</div>
					</div>
				</div>
				
				<button class="btn btn-success">Adicionar</button>
			</fieldset>
		</form>
	</div>
</div>