<div class="container">
	<div class="row pt-5 px-5">
		<div class="col-md-12 px-4 col-sm-12  mb-2" style="font-size: 15px; margin: auto;" align="center">
			<nav class="navbar navbar-expand-lg">
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item mr-1">
					        <a class="nav-link link-option desable-link alert alert-primary" id="pessoal" href="/candidato/info">Pessoais</a>
					    </li>
					    <li class="nav-item mr-1">
					        <a class="nav-link link-option desable-link alert alert-primary" id="formacao" href="<?= (isset($this->view->registro) && $this->view->registro[0]->getCurso() != false) ? '/curso/index' : '/curso/adicionar'?>">Formação</a>
					    </li>
					    <li class="nav-item mr-1">
					        <a class="nav-link link-option desable-link alert alert-primary" id="experiencia" href="<?= (isset($this->view->registro) && $this->view->registro[0]->getExperiencia() != false) ? '/experiencia/index' : '/experiencia/adicionar'?>">Experiencias</a>
					    </li>
					</ul>
				</div>
			</nav>
		</div>
	</div>
	<div class="row pb-5 px-5" align="center">
		<div class="col"><h2>Info. experiencias</h2></div>
	</div>
	<div class="row pb-5 px-5" align="center" >
		<div class="col-md-12 col-sm-12" align="right">
			<table class="table table-md table-sm table-responsive-md table-responsive-sm table-hover">
				<thead>
					<tr>
						<th>Cargo</th>
						<th>Empresa</th>
						<th>Atual ?</th>
						<th>Início</th>
						<th>Fim</th>
						<th>Ação</th>
					</tr>
				</thead>
				<tbody>
					<?php 

						for ($i=0; !($i == count($this->view->registros) ); $i++) { 
							
					?>

					<tr>
						<td><?=$this->view->registros[$i]->getCargo();?></td>
						<td><?=$this->view->registros[$i]->getNomeEmpresa();?></td>
						<td><?=$this->view->registros[$i]->getAtual();?></td>
						<td><?=$this->view->registros[$i]->getDtInicio();?></td>
						<td><?=$this->view->registros[$i]->getDtFim();?></td>
						<td>
							<a href="#" class="btn btn-sm btn-outline-success">Visualizar</a>
							<a href="/experiencia/editar?experiencia=<?=$this->view->registros[$i]->getIdExperiencia();?>" class="btn btn-sm btn-outline-primary">Editar</a>
							<a href="#" class="btn btn-sm btn-outline-danger">Excluir</a>
						</td>
					</tr>
					<?php 

						}
					?>




				</tbody>
			</table>
		</div>
	</div>
	<div class="row pb-5 px-5">
		<div class="col" align="left">
			<a href="/experiencia/adicionar" class="btn btn-sm btn-outline-success">Adicionar</a>
		</div>
	</div>
</div>