<div class="container">
	<div class="row pt-5 px-5">
		<div class="col-md-12 px-4 col-sm-12  mb-2" style="font-size: 15px; margin: auto;" align="center">
			<nav class="navbar navbar-expand-lg">
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item mr-1">
					        <a class="nav-link link-option desable-link alert alert-primary" id="pessoal" href="/candidato/adicionar">Pessoais</a>
					    </li>
					    <li class="nav-item mr-1">
					        <a class="nav-link link-option desable-link alert alert-primary" id="formacao" href="/curso/adicionar">Formação</a>
					    </li>
					    <li class="nav-item mr-1">
					        <a class="nav-link link-option desable-link alert alert-secondary" id="experiencia" href="/experiencia/adicionar">Experiencias</a>
					    </li>
					</ul>
				</div>
			</nav>
		</div>
	</div>
	<div class="row pb-5 px-5">
		<form class="col" method="post" action="/candidato/savar">
			<fieldset><legend>Cursos</legend>
				<div class="row">
					<div class="col">
						<div class="form-group">
							<label for="nome">Nome</label>
							<input type="text" name="nome" id="nome"class="form-control form-control-sm" required="required">
						</div>
						<div class="form-group">
							<label for="instituicao">Instituição</label>
							<input type="text" name="instituicao" id="instituicao"class="form-control form-control-sm" required="required">
						</div>
						<div class="form-group">
							<label for="turno">Nível</label>
							<select name="turno" id="turno"class="form-control form-control-sm" required="required">
								<option value="1">Medio</option>
								<option value="2">Profissionalizante</option>
								<option value="3">Técnico</option>
								<option value="4">Graduação</option>
								<option value="5">Pós-Graduação</option>
							</select>
						</div>
						<div class="form-group">
							<label for="inico">Inicio</label>
							<input type="date" name="inico"id="inico" class="form-control form-control-sm" required="required">
						</div>
					</div>
					<div class="col">
						<div class="form-group">
							<label for="termino">Termino</label>
							<input type="date" name="termino" id="termino"class="form-control form-control-sm" required="required">
						</div>
						<div class="form-group">
							<label for="status">Status</label>
							<select name="status" id="status"class="form-control form-control-sm" required="required">
								<option value="1">Cursando</option>
								<option value="2">Trancado</option>
								<option value="3">Concluido</option>
							</select>
						</div>
						<div class="form-group">
							<label for="turno">Turno</label>
							<select name="turno" id="turno"class="form-control form-control-sm" required="required">
								<option value="1">Matutino</option>
								<option value="2">Vespertino</option>
								<option value="3">Noturno</option>
							</select>
						</div>
					</div>

				</div>
				
							
				<button class="btn btn-success">Adicionar</button>
			</fieldset>
		</form>
	</div>
</div>