<div class="container">
	<div class="row pt-5 px-5">
		<div class="col-md-12 px-4 col-sm-12  mb-2" style="font-size: 15px; margin: auto;" align="center">
			<nav class="navbar navbar-expand-lg">
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item mr-1">
					        <a class="nav-link link-option desable-link alert alert-primary" id="pessoal" href="/candidato/info">Pessoais</a>
					    </li>
					    <li class="nav-item mr-1">
					        <a class="nav-link link-option desable-link alert alert-primary" id="formacao" href="<?= (isset($this->view->registro) && $this->view->registro[0]->getCurso() != false) ? '/curso/index' : '/curso/adicionar'?>">Formação</a>
					    </li>
					    <li class="nav-item mr-1">
					        <a class="nav-link link-option desable-link alert alert-secondary" id="experiencia" href="<?= (isset($this->view->registro) && $this->view->registro[0]->getExperiencia() != false) ? '/experiencia/index' : '/experiencia/adicionar'?>">Experiencias</a>
					    </li>
					</ul>
				</div>
			</nav>
		</div>
	</div>
	<div class="row pb-5 px-5">
		<form class="col" method="post" action="/curso/atualizar">
			<fieldset><legend>Cursos</legend>
			<input type="hidden" name="curso" value="<?=$this->view->dados[0]->getIdCurso();?>">
				<div class="row">
					<div class="col">
						<div class="form-group">
							<label for="nome">Nome</label>
							<input type="text" name="nome" id="nome"class="form-control form-control-sm" required="required" value="<?=$this->view->dados[0]->getNome();?>">
						</div>
						<div class="form-group">
							<label for="instituicao">Instituição</label>
							<input type="text" name="instituicao" id="instituicao"class="form-control form-control-sm" required="required"  value="<?=$this->view->dados[0]->getInstituicao();?>" >
						</div>
						<div class="form-group">
							<label for="tipo">Tipo</label>
							<select name="tipo" id="tipo"class="form-control form-control-sm" required="required">
								<option <?= ( $this->view->dados[0]->getTipo() =='graduacao' ) ? 'selected': '' ?> value="graduacao" >Graduação</option>
								<option <?= ( $this->view->dados[0]->getTipo() =='pos-graduacao' ) ? 'selected': '' ?> value="pos-graduacao">Pós-Graduação</option>
								<option <?= ( $this->view->dados[0]->getTipo() =='profissionalizante' ) ? 'selected': '' ?> value="profissionalizante" value="2">Profissionalizante</option>
								<option  <?= ( $this->view->dados[0]->getTipo() =='especializacao' ) ? 'selected': '' ?> value="especializacao">Especialização</option>
							</select>
						</div>
						<div class="form-group">
							<label for="inico">Inicio</label>
							<input type="date" name="inico"id="inico" class="form-control form-control-sm" required="required" value="<?=$this->view->dados[0]->getDtInicio();?>">
						</div>
					</div>
					<div class="col">
						<div class="form-group">
							<label for="termino">Termino</label>
							<input type="date" name="termino" id="termino"class="form-control form-control-sm" required="required" value="<?=$this->view->dados[0]->getDtTermino();?>">
						</div>
						<div class="form-group">
							<label for="status">Status</label>
							<select name="status" id="status"class="form-control form-control-sm" required="required">
								<option <?= ( $this->view->dados[0]->getStatus() =='cursando' ) ? 'selected': '' ?> value="cursando" >Cursando</option>
								<option <?= ( $this->view->dados[0]->getStatus() =='trancado' ) ? 'selected': '' ?> value="trancado">Trancado</option>
								<option <?= ( $this->view->dados[0]->getStatus() =='concluido' ) ? 'selected': '' ?> value="concluido">Concluido</option>
							</select>
						</div>
						<div class="form-group">
							<label for="turno">Turno</label>
							<select name="turno" id="turno"class="form-control form-control-sm" required="required">
								<option <?= ( $this->view->dados[0]->getTurno() =='matutino' ) ? 'selected': '' ?> value="matutino" >Matutino</option>
								<option <?= ( $this->view->dados[0]->getTurno() =='vespertino' ) ? 'selected': '' ?> value="vespertino">Vespertino</option>
								<option <?= ( $this->view->dados[0]->getTurno() =='noturno' ) ? 'selected': '' ?> value="noturno" >Noturno</option>
							</select>
						</div>
						<div class="form-group">
							<label for="modalidade">Modalidade</label>
							<select name="modalidade" id="modalidade"class="form-control form-control-sm" required="required">
								<option <?= ( $this->view->dados[0]->getModalidade() =='ead' ) ? 'selected': '' ?> value="ead" >Ead</option>
								<option <?= ( $this->view->dados[0]->getModalidade() =='presencial' ) ? 'selected': '' ?> value="presencial">Presencial</option>
								<option <?= ( $this->view->dados[0]->getModalidade() =='semepresencial' ) ? 'selected': '' ?> value="semepresencial" >Semipresencial</option>
							</select>
						</div>
					</div>

				</div>
							
				<button class="btn btn-success">Atualizar</button>
				<a class="btn btn-md btn-outline-danger" href="<?= (isset($this->view->registro) && $this->view->registro[0]->getCurso() != false) ? '/curso/index' : '/curso/adicionar'?>">Cancelar</a>
			</fieldset>
		</form>
	</div>
</div>