<div class="row py-5 px-5">
	<div class="col-md-9 px-4 col-sm-12  mb-2" style="font-size: 15px;">
		<div class="row">
			<div class="col p-4 mb-2 mr-2 rounded border bg-white col-shadow">
				<form>
					<div class="form-group">
						<label for="vaga">Vaga</label>
						<input id="vaga" type="text" name="vaga" class="form-control">
					</div>
					<div class="form-group">
						<label for="onde">Onde?</label>
						<input id="onde" type="text" name="onde" class="form-control">
					</div>
					<center><button type="submit" class="btn btn-md btn-outline-primary">Buscar Vagas</button></center>
				</form>
			</div>
			<div class="col p-4 mb-2 mr-2 rounded  border bg-white col-shadow">
				<h5 align="left">Notificações do admin</h5>
				<div class="row mt-2">
					
				</div>
			</div>
			<div class="col p-4 mb-2 mr-2 rounded border bg-white col-shadow">
				<h5 align="center">Resumo de candidaturas</h5>
				<div class="row mt-2">
					<div class="col">
						<div>0</div>
						<div>CV Enviado</div>
					</div>
					<div class="col">
						<div>0</div>
						<div>Em Processo</div>
					</div>
					<div class="col">
						<div>0</div>
						<div>CV Finalista</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col p-4 mb-2 mr-2 rounded border bg-white col-shadow">
				<h5 align="center">Cursos recomendados</h5>
				<div class="row">
					<div class="col-md-12 col-sm-12">
						<h5>Ingles</h5>
						<div>Informatize</div>
						<div>Online</div>
						<hr>
					</div>
				</div>
				
				<a href="#" class="btn btn-md btn-outline-primary">Ver mais</a>
			</div>
			<div class="col p-4 mb-2 mr-2  border bg-white col-shadow">
				<h5 align="center">Melhore seu CV</h5>
				<p align="center" class="mt-5">com testes e simulados</p>
				<p align="center"><a href="#" class="btn btn-md btn-outline-primary desable-link">Seja premium</a></p>
			</div>
			<div class="col p-4 mb-2 mr-2 border bg-white col-shadow">
				<h5 align="center">Novas mensagens</h5>
				<div class="row mt-5">
					<div class="col" align="center" style="vertical-align: center; height: 100%;">
						<p>2</p>
						<p><a href="#" class="btn btn-md btn-outline-primary desable-link">Visualizar</a></p>
					</div>
				</div>
			</div>
		</div>	
	</div>
	<div class="col-md-3 p-4 col-sm-12 bg-white col-shadow">
		<h4 align="center" style="font-size: 20px;">Vagas de seu interesse</h5>
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<h6>Coordenador de loja</h6>
				<div>Serhum RH</div>
				<div>São Luis, MA</div>
				<div>07/07 07:07</div>
				<hr>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<h6>Coordenador de loja</h6>
				<div>Serhum RH</div>
				<div>São Luis, MA</div>
				<div>07/07 07:07</div>
				<hr>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<h6>Coordenador de loja</h6>
				<div>Serhum RH</div>
				<div>São Luis, MA</div>
				<div>07/07 07:07</div>
				<hr>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<h6>Coordenador de loja</h6>
				<div>Serhum RH</div>
				<div>São Luis, MA</div>
				<div>07/07 07:07</div>
				<hr>
			</div>
		</div>
		<a href="#" class="btn btn-md btn-outline-primary desable-link">Ver mais</a>
	</div>
</div>

<div class="row py-5 px-5">
	<div class="col">
		<h3 align="center">Seja premium</h3>
	</div>
</div>