<div class="row">
	<div class="col" align="right">
		<nav class=" navbar-expand-lg navbar-light" style="float: right;">
			<ul class="navbar-nav mr-auto">
		      <li class="nav-item active">
		        <a class="nav-link" href="/">Home</a>
		      </li>
		      <li class="nav-item active">
		      	<span class="nav-link" style="cursor: default;">/</span>
		      </li>
		      <li class="nav-item active">
		        <a class="nav-link">Login</a>
		      </li>
		    </ul>
		</nav>
	</div>
</div>
<div class="row">
	<div class="col" align="" style="height: 700px;">
		<form class="form py-5 px-5" method="post" action="/usuario/logar" style="" id="login">
			<fieldset><legend  align="center" class="h1"><center>Login</center></legend>
				<div class="form-group">
					<label for="usuario">Usuario:</label>
					<input required="required" id="usuario" type="email" name="usuario" class="form-control form-control-sm">
				</div>
				<div class="form-group">
					<label for="senha">Senha:</label>
					<input required="required" id="senha" type="password" name="senha" class="form-control form-control-sm">
				</div>
				<div class="form-group" style="display: flex; justify-content: space-between;">
					<button class="btn btn-xs btn-primary">Entrar</button>
					<a class="nav-link" href="#"><small>Ainda não sou cadastrado.</small></a>
				</div>
				
			</fieldset>
		</form>
	</div>
</div>