<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="../styles/bootstrap-4/css/bootstrap.min.css">
    <link rel="stylesheet" href="../styles/bootstrap-4/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="../styles/more_styles/jobs_style.css">
    <link rel="stylesheet" href="../fontawesome/css/all.css">
    <link rel="stylesheet" href="../jquery/jquery-ui/jquery-ui.min.css">
    
    <script src="../jquery/jquery.min_google.js"></script>
    <script src="../jquery/jquery-ui/jquery-ui.min.js"></script>
    <script src="../jquery/plugins/elevatezoom-master/jquery.elevatezoom.js" type="text/javascript"></script>
    <script src="../styles/bootstrap-4/js/bootstrap.min.js"></script>
    <script src="../fontawesome/js/all.js"></script>
    <!--<script type="text/javascript" src=
"https://stc.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js"></script>-->
<script type="text/javascript" src=
"https://stc.sandbox.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js"></script>
    
    <script src="../js/jobs.js"></script>

    <script src="../ajax/pagseguro.js"></script>
    <script type="text/javascript" src="../js/bibliotecas/chart.js"></script>
    <title>Minha-Loja.com</title>
</head>
  <body id="bodyLojaVirtual">
      <header>
          <?php $this->loadMenu(); ?>
      </header>
      <?php
        $msg = Core\Utilitarios\Sessoes::getMessage();

        if($msg){
      ?>
      <section style="" id="section-response">
        <div class="container-fluid">
          <div class="row">
              <div class="col alert alert-<?=$msg[1]?> alert-dismissible fadeshow" id="msg-response" align="center" style="">
                <button class="close" data-dismiss = 'alert'>&times</button>
                <?=$msg[2]?>
              </div>
          </div>
        </div>
      </section>
      <?php 

        }else{

      ?>
        <section style="display: none;" id="section-response">
        <div class="container-fluid">
          <div class="row">
              <div class="col alert alert-dismissible fadeshow" id="msg-response" align="center" style="">
              </div>
          </div>
        </div>
      </section>

      <?php
        }
      ?>
      <section class="" style="flex: 1 0 auto;" id="container-principal">
        <?php $this->content($view_path); ?>
      </section>
      <footer>

        <?php $this->loadFooter(); ?>

      <!-- The Modal -->
      <div class="modal fade" id="myModal">
        <div class="modal-dialog modal-sm modal-lg modal-xl modal-dialog-centered">
          <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
              <h4 class="modal-title">Modal Heading</h4>
              <button type="button" class="close" data-dismiss="modal" id="closeModal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
              Modal body..
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
              
            </div>

          </div>
        </div>
      </div>

      </footer>
  </body>
</html>