
<nav class="navbar navbar-expand-lg navbar-light alert-primary" id="nav-home-site">
	<div class="container">
	  <a class="navbar-brand desable-link" href="/">Find-Jobs</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active mr-1">
	        <a class="nav-link desable-link" href="#">Publicar vaga <span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item mr-1">
	        <a class="nav-link desable-link" href="#">Encontrar vaga</a>
	      </li>
	      <li class="nav-item mr-1">
	        <a class="nav-link desable-link" href="#">Encontrar empresa</a>
	      </li>
	      <li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle desable-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Mais
	        </a>
	        <div class="dropdown-menu navbar-light alert-primary" aria-labelledby="navbarDropdown">
	          <a class="dropdown-item desable-link" href="#">Notícias</a>
	          <a class="dropdown-item desable-link" href="#">Blog</a>
	          <div class="dropdown-divider"></div>
	          <a class="dropdown-item desable-link" href="#">Something else here</a>
	        </div>
	      </li>
	    </ul>
	    <div class="row my-2 my-lg-0">
	      	<ul class="navbar-nav mr-auto">
		      <li class="nav-item">
		        <a class="nav-link desable-link" href="#">Cadastre sua empresa</a>
		      </li>
		      <li class="nav-item ">
		        <a class="nav-link login desable-link" href="/usuario/index" >Login <span class="sr-only">(current)</span></a>
		      </li>
	  		</ul>
	    </div>
	  </div>
  </div>
</nav>
