<div class="container-fluid py-5 px-5">
	<div class="row">
		<div class="col">
			<div class="container py-5 px-5" style="background-color: #fff;">
				<div class="row">
					<div class="col-md-8 col-sm-6">
						<div class="row">
							<div class="col">Institucional</div>
							<div class="col">Empresa</div>
							<div class="col">Candidato</div>
						</div>
					</div>
					<div class="col-md-4 col-sm-6">
						<div class="row">
							<div class="col">Wha</div>
							<div class="col">Inst</div>
							<div class="col">Fac</div>
							<div class="col">Twi</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="container-fluid py-5 px-5 bg-light">
	<div class="row">
		<div class="col" align="center">
			<h2>Find-Jobs</h2>
			<sub>Todos os direitos reservados</sub>
		</div>
	</div>
</div>