
<nav class="navbar navbar-expand-lg navbar-light alert-primary" id="nav-menu">
	<div class="container">
	  <a class="navbar-brand" href="/candidato/index"><?=$this->view->registro[0]->getNome();?></a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	    	<li class="nav-item active mr-1 dropdown">
	    		<a class="nav-link dropdown-toggle desable-link" href="#" id="minha-area" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Minha area
	        </a>
	        <!-- link-option -> classe para links -->
	        <div class="dropdown-menu navbar-light alert-primary" aria-labelledby="minha-area">
	          <a class="dropdown-item  desable-link" href="#">Vagas exclusivas pra você</a>
	          <a class="dropdown-item  desable-link" href="#">Destaques do seu CV</a>
	          <a class="dropdown-item  desable-link" href="#">Visualizações do seu CV</a>
	          <a class="dropdown-item  desable-link" href="#">Evios diretos de CV</a>
	          <a class="dropdown-item  desable-link" href="#">Blog</a>
	          <a class="dropdown-item  desable-link" href="#">Testes de avaliações</a>
	          <a class="dropdown-item  desable-link" href="#">Simulador de Entrevistas</a>
	        </div>
	      </li>
	      <li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle desable-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Mais
	        </a>
	        <div class="dropdown-menu navbar-light alert-primary" aria-labelledby="navbarDropdown">
	          <a class="dropdown-item  desable-link" href="#">Mensagens</a>
	          <a class="dropdown-item  desable-link" href="#">Cursos</a>
	          <a class="dropdown-item  desable-link" href="#">Meus aviso</a>
	          <a class="dropdown-item  desable-link" href="#">Notícias</a>
	          <a class="dropdown-item  desable-link" href="#">Blog</a>
	          <a class="dropdown-item  desable-link" href="#">Sua conta</a>
	          <a class="dropdown-item" href="/usuario/sair">Sair</a>
	        </div>
	      </li>
	      <li class="nav-item mr-1">
	        <a class="nav-link  desable-link" href="#">Candidaturas <span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item mr-1">
	        <a class="nav-link  desable-link" href="#">Buscar vaga</a>
	      </li>
	      <li class="nav-item mr-1">
	        <a class="nav-link  desable-link" id="curriculo" href="/candidato/curriculo">Curriculo</a>
	      </li>
	      <li class="nav-item mr-1">
	        <a class="nav-link  desable-link" href="#">Empresas</a>
	      </li>
	    </ul>
	  </div>
  </div>
</nav>